### ISSUE TITLE
Question about schema

### ISSUE THREAD

**Issue by oktayaa** [dnknth/ldap-ui#1]
I've tried a few web frontends and they all make assumptions about the underlying schema. I am using inetOrgPerson records exclusively but the ones I tried are kind of unixy and require home directories and things like that. Is this a generic client?

By the way phpldapadmin has been getting updates lately. It's at https://github.com/leenooks/phpLDAPadmin . I don't know if the person is one of the original developers but the fixes work well.

**Comment by dnknth** [comment]
Hello @oktayaa ,

The UI does not care about the LDAP schema. It loads the class and attribute definitions from the server (so you can look up the schema), but otherwise only a few attributes are hard-wired. Off the top of my head I believe that only `objectClass`, `jpegPhoto` and `userPassword` are treated specially. Also, there is currently a fixed list of DN-valued attributes for search. The rest is generic.

But of course if you add a `posixAccount` auxillary class, it comes with a bunch of required attributes. That is dictated by the schema, and the editor will pull them in. For `inetOrgPerson`, only `sn` is mandatory as per schema.

**Comment by oktayaa** [comment]
Thank you. I will test the docker image in a bit. I got sidetracked and
decided to upgrade my docker environment first as we all do. Thanks again.
