### ISSUE TITLE
Vue CDN Error

### ISSUE THREAD

**Issue by hetz** [dnknth/ldap-ui#59]
When I run `docker run -di --name my_dnknth_ldap-ui --restart=always -p 5000:5000 -e TZ=Asia/Shangha -e LDAP_URL=ldap://ldap.forumsys.com:389/ -e BASE_DN=dc=example,dc=org dnknth/ldap-ui:latest`

I open browser `http://localhost:5000`get error

<img width="1438" alt="image" src="https://github.com/dnknth/ldap-ui/assets/820141/a7e2f39f-04f9-4949-8579-005c10117ac7">

**Comment by dnknth** [comment]
Hello @hetz,

The `ldap-ui` version in the screenshot is outdated. Since d463a6e4accf2aa8f2999828fd3c3c2927cd3b76 it does not rely on `bootstrap-vue` any more, and all assets are served locally. Please try again with a fresh image.

Also, I am unsure whether the environment options given on the command line make any difference.

**Comment by hetz** [comment]
> Hello @hetz,
> 
> The `ldap-ui` version in the screenshot is outdated. Since [d463a6e](https://github.com/dnknth/ldap-ui/commit/d463a6e4accf2aa8f2999828fd3c3c2927cd3b76) it does not rely on `bootstrap-vue` any more, and all assets are served locally. Please try again with a fresh image.
> 
> Also, I am unsure whether the environment options given on the command line make any difference.

Thx you reply, I check my images version.

this wrong like docker.io ?
I get pull latest tag ,but get image date with 4 years old.
![image](https://github.com/dnknth/ldap-ui/assets/820141/13eaa3ef-cec3-401f-95fa-c2d13ac7a5de)

**Comment by dnknth** [comment]
Have you checked [Docker Hub](https://hub.docker.com/r/dnknth/ldap-ui/tags)?
